name: Publish

on:
    workflow_run:
        workflows: [Build]
        branches: [main]
        types: [completed]

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  id-token: write
  pull-requests: write
  contents: write

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v6
          - uses: actions/setup-node@v6
            with:
                node-version: 24
                registry-url: https://registry.npmjs.org/
                package-manager-cache: false

          - name: PNPM
            uses: pnpm/action-setup@v2
            with:
                version: latest

          - name: Installation
            run: pnpm i --frozen-lockfile

          - name: Make PR or publish
            id: changesets
            uses: changesets/action@v1
            with:
                publish: pnpm run release
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}